### ISSUE TITLE
How to pass multiple params

### ISSUE THREAD

**Issue by rajkaran** [fcorti/adf-pentaho-project#1]
I am try below code
```
<div >
    <input [(ngModel)]="groupBy" placeholder="name" id="group-by">
    <input [(ngModel)]="physician" placeholder="name" id="physician-lastName">

    <pentaho-dashboard
        id = "parent"
        pentahoPath = "/public/embed_pentaho_internally/dashboard/drilldown/child_dashboard.wcdf"
        [params] = "['groupBy', 'physicianLastName']"
        masterHtmlElementId = "[group-by, physician-lastName]">
    </pentaho-dashboard>
</div>
```

**Comment by fcorti** [comment]
Hi Raj,

It is a limitation related to the masterHtmlElementId attribute that accepts only a single value.
Let me experiment a little bit and I'll confirm here if I'll be able to manage the array of params.

Cheers.

**Comment by fcorti** [comment]
Ok, experimentation went well.
I'll extend the feature into the next release (1.0.3).
Thank you for submitting your use case here.
I'll create the next release in few days.
Stay tuned...

**Comment by fcorti** [comment]
Ok, released into the 1.0.2 version of the package.
Let me know if it works well.

Cheers.

**Comment by rajkaran** [comment]
Hi @fcorti 

sorry it took me sometime to test new changes.

Works pretty well. below is the template code that worked for me.
```
<pentaho-dashboard
        id = "drilldown"
        pentahoPath = "/public/basic-cde-samples/show-received-params.wcdf"
        [params] = "['p_from_datetime', 'p_to_datetime', 'p_group_by', 'p_physician_lastname']"
        [masterHtmlElementIds] = "['from-datetime', 'to-datetime', 'group-by', 'physician-lastName']" >
</pentaho-dashboard>
```

**Comment by fcorti** [comment]
Nice to hear!
Could be great if you could "like" the project, if this is the case.
