### ISSUE TITLE
Two interacting dashboards not behaving right

### ISSUE THREAD

**Issue by rajkaran** [fcorti/adf-pentaho-project#4]
I have this in my dashboard3.component template

```
<div>
    <pentaho-dashboard
        id = "dashboard3"
        pentahoPath = "/public/basic-cde-samples/sample1.wcdf">
    </pentaho-dashboard>

    <pentaho-dashboard
        id = "dashboard4"
        pentahoPath = "/public/basic-cde-samples/sample2.wcdf"
        [params] = "['param2']"
        masterDashboardId = "dashboard3"
        [masterDashboardParams] = "['param1']">
    </pentaho-dashboard>
</div>
```
On running application I am seeing sample2 dashboard two times.

![screencapture-localhost-4200-dashboard3-1516898248754](https://user-images.githubusercontent.com/4390019/35400243-3473f558-01c4-11e8-829b-c5bd3aefefc9.png)

I followed your gitbook tutorial https://fcorti.gitbooks.io/pentaho-dashboard-project/content/viewing-a-dashboard/viewing-two-interacting-dashboards.html

Assuming dashboard2 was typo in statement 

> 2. Developing the Dashboard3Component
Once done, it's time to develop the dashboard2 component.

**Comment by rajkaran** [comment]
Found the reason why it's happening, `currentDashboard` and `masterDashboard` are the object of same dashboard.

While playing with it I have made couple of tweaks.

Added a new function.
```
private getJsCodeMultipleRequireStart(paths: string[]):string {
      var result = "require([";
      for (let i in paths) {
          if(i > 0) result += ',';
          result += "\"dash!" + paths[i] + "\"";
      }
    return result + "] ";
  }
```

Call new function in 'renderDashboardDependingOnDashboard'
```
var masterPath = document.getElementById(masterDashboardHtmlId).getAttribute('pentahoPath');

    var jsCode = "";
    // jsCode += this.getJsCodeRequireStart(path);
    jsCode += this.getJsCodeMultipleRequireStart([masterPath, path]);
    jsCode += this.getJsCodeForDashboardDependingOnDashboard(htmlId, params, masterDashboardHtmlId, masterParams);
    jsCode += this.getJsCodeRequireEnd();
```

Change in `getJsCodeForDashboardDependingOnDashboard'
```
var jsCode = ", function(MasterDashboard, Dashboard) { ";
    jsCode += "var currentDashboard = new Dashboard(\"" + htmlId + "\"); ";
    jsCode += "currentDashboard.render(); ";
    jsCode += "var masterDashboard = new MasterDashboard(\"" + masterDashboardHtmlId + "\"); ";
    jsCode += "masterDashboard.render(); ";
    for (let i in masterParams) {
      jsCode += "masterDashboard.on(\"cdf " + masterParams[i] + ":fireChange\", function (evt) { currentDashboard.fireChange(\"" + params[i] + "\", evt.value); }); ";
    }
    jsCode += "} ";
```

**Comment by fcorti** [comment]
Typo in documentation solved.
Thanks for pointing on this.

**Comment by fcorti** [comment]
Well done raijkaran!

I had to change a little bit the getJsCodeMultipleRequireStart because the "if(i>0)" was not working, but it's a good solution.
Thank you for the contribution.
The fix has been included in the project.

**Comment by rajkaran** [comment]
Thank you,

Have you released a new version with this change?

**Comment by fcorti** [comment]
Yep!
Already on npm.

https://github.com/fcorti/pentaho-dashboard-project/releases/tag/1.0.3
