### ISSUE TITLE
Connect to a remote pentaho server via https protocol

### ISSUE THREAD

**Issue by abiantorres** [fcorti/adf-pentaho-project#5]
I'm developing a web app under the https protocol. When using your tool, I have encountered several problems. In your tutorials, the proxy configuration is done via http, however, my application and remote pentaho server run under https, as previously commented.

The **proxy.conf.json** file looks like this one:

```
{
  "/pentaho": {
  	"target":  {
       "host": "my.external.server",
       "protocol": "https:",
       "port": myport
    },
    "secure": false,
    "changeOrigin": true,
    "logLevel": "debug"
  }
}
```

And the **login submit method**:

```
  onSubmit(username:string, password:string) 
  {
    if (this.pentahoDashboardService.isLoggedIn()) {
      this.pentahoDashboardService.logIn('/');
    }
    else {
      this.pentahoDashboardService.setUsername(username);
      this.pentahoDashboardService.setPassword(password);
      this.pentahoDashboardService.logIn('/');
      if (this.pentahoDashboardService.isNotLoggedIn()) {
        this.loginMessage = 'No se ha podido establecer la conexión. Inténtelo de nuevo.';
        return false;
      }
    }
  } 
```

Also, when I run the first time my application  I get this warning and error:

```
zone.js:2191` [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
(anonymous) @ zone.js:2191
open @ VM41662:3
(anonymous) @ scripts.bundle.js:63240
zone.js:2197 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://myhost:myport/pentaho/Home'.
```

Finally, when I'm trying to get logged in catching correctly the data from a form I receive a 0 code error. I'm not sure if it's possible to use your package using the https protocol, or it's some implementation error of mine.
Congratulations for your work and effort.

**Comment by fcorti** [comment]
Hi Abian,

The error you get is correct and it is related to the very first call to one of the Pentaho services.
I'm still continuing to think that the proxy.conf.json should be the issue.
Looking at the error the `host` value could be wrong.

Please investigate more there... and let me know.
I'm always interested to understand problems and solutions.

**Comment by abiantorres** [comment]
I was using the pentaho server IP instead of the **domain name**.  Nevertheless, now I get a `405 ` error:

```
Failed to load https://my.pentaho.domain:port/pentaho/Login: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://my.web.application.domain:port' is therefore not allowed access. The response had HTTP status code 405.
```

Also, I'm still getting the error when the XMLHttpRequest is sended:

```
zone.js:2197 Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://my.web.application.domain:port/pentaho/Home'.
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:2197:31)
    at XMLHttpRequest.send (eval at createNamedFn (webpack-internal:///../../../../zone.js/dist/zone.js), <anonymous>:3:31)
    at https:/my.web.application.domain:port/scripts.bundle.js:63241:9
```

I don't know if it should be something related with the **XMLHttpRequest** headers.

**Comment by fcorti** [comment]
The URL does not seems to be correct.

`https://my.pentaho.domain:port/pentaho/Login`

`port` is wrong for sure.
It should have a format similar to `0000`.
IP instead of the domain name should work.

**Comment by abiantorres** [comment]
I should have indicated from the beginning that, for safety, I have omitted the real data for the port and the domain, sorry. I am using postman to do login tests and it works perfectly with the real port number and domain name.

**Comment by fcorti** [comment]
Thank you for the clarification.
Maybe the issue is due to the CORS problem using the HTTPS protocol (not sure).
Can you try to use HTTP instead, on the Pentaho side and share the result of the experiment?

**Comment by brenopolanski** [comment]
Hey @abiantorres *maybe* this is a CORS problem, try this: https://gist.github.com/brenopolanski/fce90f0090ce19bcaa3acef4af9c8eb3
